global:
  scrape_interval:     15s
  evaluation_interval: 15s


# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'dotnetruntime'
    scrape_interval: 5s
    static_configs:
      - targets: ['aspexample:5000', 'host.docker.internal:5000']


  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

